### ISSUE TITLE
Not sure how to title

### ISSUE THREAD

**Issue by faddat** [devslopes/blockchat#3]
<img width="572" alt="screen shot 2018-02-22 at 7 26 55 pm" src="https://user-images.githubusercontent.com/7142025/36538531-726310bc-1806-11e8-8425-c4c4656d027f.png">

Anyway, this seems like a really cool use of lotion.js.  

Cheers!

**Comment by faddat** [comment]
<img width="1004" alt="screen shot 2018-02-22 at 8 45 06 pm" src="https://user-images.githubusercontent.com/7142025/36541758-8433e504-1811-11e8-9335-8d54bd6c04ce.png">

**Comment by faddat** [comment]
```
admins-MacBook-Pro:build admin$ blockchat
connected
enter a username: /Users/admin/.nvm/versions/node/v8.2.1/lib/node_modules/blockchat/node_modules/supercop.js/lib.js:97
      throw ex;
      ^

Error: connect ECONNREFUSED 159.65.168.34:46657
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
```

Now happens when trying to connect to blockchat
