### ISSUE TITLE
Cannot run app

### ISSUE THREAD

**Issue by Ajay-invin** [devslopes/blockchat#4]
This error pops while running this app

C:\Windows\system32>blockchat
connected
enter a username: C:\Users\wVw_PC\AppData\Roaming\npm\node_modules\blockchat\nod
e_modules\supercop.js\lib.js:97
      throw ex;
      ^

Error: connect ECONNREFUSED 159.65.168.34:46657
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)

C:\Windows\system32>

**Comment by anarkrypto** [comment]
I have this same error. Mac OS Hight Sierra Version 10.13.3

When I try the install, I receive this error: 
$ npm install blockchat -g
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.3: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
/Users/kaiquenunes/.nvm/versions/node/v8.2.1/bin/blockchat -> /Users/kaiquenunes/.nvm/versions/node/v8.2.1/lib/node_modules/blockchat/bin/chat-client.js
+ blockchat@1.0.1
updated 1 package in 11.514s


So if I try to run: 
$ blockchat
connected
enter a username: /Users/kaiquenunes/.nvm/versions/node/v8.2.1/lib/node_modules/blockchat/node_modules/supercop.js/lib.js:97
      throw ex;
      ^

Error: connect ECONNREFUSED 159.65.168.34:46657
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)

**Comment by anarkrypto** [comment]
I used "nvm use 8.2"

And I already updated to graceful-fs@4.1.11

But still not working. The same error.
